version: '3.7'

services:
  qfrontend:
    container_name: q-frontend
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/:/client
    ports:
      - 3000:3000
    links:
      - qbackend
    networks:
      - default

    command: npm run start
  
  qbackend:
    container_name: q-backend
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
    ports:
      - 5000:5000
    networks:
      - default

    command:  uwsgi --http 0.0.0.0:5000 --master --wsgi-file /server/server.py --ini /server/server.ini --http-to /tmp/server.sock
    
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PYTHONPATH=/server

networks:
  default:
    external: false
